### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by netantho** [alco/commando#2]
@alco I have some patches that I would like to contribute (updating to elixir 1.3.x and fixing warnings due to upgrade, fix some bugs) but I can't legally do so without a LICENSE file at the root of the repo.
I could contribute if you choose one of the following licenses: Apache 2, MIT, BSD or GPL.
Thanks!
Btw, great project!

**Comment by alco** [comment]
Hi @netantho,

Sorry for the long wait. This project hasn't been maintained in years.

I've added a license. If you plan to develop it further, I can give you commit rights.

Cheers.
